// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presentacion.Modelos;

namespace Presentacion.Migrations
{
    [DbContext(typeof(DbNatatorioContext))]
    [Migration("20211012180915_AgregamosDireccionYSocioGarante")]
    partial class AgregamosDireccionYSocioGarante
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Presentacion.Modelos.Cobrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cobradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Fernandez",
                            Nombre = "José"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gonzalez",
                            Nombre = "Gustavo"
                        });
                });

            modelBuilder.Entity("Presentacion.Modelos.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Dirección")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocioGaranteId")
                        .HasColumnType("int");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.Property<string>("Teléfono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SocioGaranteId");

                    b.ToTable("Socios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Perez",
                            DNI = 12121212,
                            Nombre = "Juan",
                            SocioId = 0,
                            Teléfono = "34343434"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gomez",
                            DNI = 12787878,
                            Nombre = "Adrian",
                            SocioId = 0,
                            Teléfono = "98989898"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rodriguez",
                            DNI = 56565656,
                            Nombre = "Pedro",
                            SocioId = 0,
                            Teléfono = "45454545"
                        });
                });

            modelBuilder.Entity("Presentacion.Modelos.Socio", b =>
                {
                    b.HasOne("Presentacion.Modelos.Socio", "SocioGarante")
                        .WithMany()
                        .HasForeignKey("SocioGaranteId");
                });
#pragma warning restore 612, 618
        }
    }
}
