// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presentacion.Modelos;

namespace Presentacion.Migrations
{
    [DbContext(typeof(DbNatatorioContext))]
    [Migration("20211103185024_agregamosCuota")]
    partial class agregamosCuota
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NatatorioCEF.Modelos.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<float>("Cobrado")
                        .HasColumnType("real");

                    b.Property<int?>("CobradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<float>("Importe")
                        .HasColumnType("real");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<float>("Recargo")
                        .HasColumnType("real");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CobradorId");

                    b.HasIndex("SocioId");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("NatatorioCEF.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador",
                            Password = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            TipoUsuario = 1,
                            User = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "empleado",
                            Password = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            TipoUsuario = 3,
                            User = "empleado"
                        });
                });

            modelBuilder.Entity("Presentacion.Modelos.Cobrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cobradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Fernandez",
                            Nombre = "José"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gonzalez",
                            Nombre = "Gustavo"
                        });
                });

            modelBuilder.Entity("Presentacion.Modelos.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "San Justo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Gobernador Crespo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Llambi Campbell"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Ramayón"
                        });
                });

            modelBuilder.Entity("Presentacion.Modelos.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Dirección")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocioGaranteId")
                        .HasColumnType("int");

                    b.Property<string>("Teléfono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.HasIndex("SocioGaranteId");

                    b.ToTable("Socios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Perez",
                            DNI = 12121212,
                            Dirección = "9 de julio 1232",
                            LocalidadId = 1,
                            Nombre = "Juan",
                            SocioGaranteId = 1,
                            Teléfono = "34343434"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gomez",
                            DNI = 12787878,
                            Dirección = "Pedro Millán 1212",
                            LocalidadId = 1,
                            Nombre = "Adrian",
                            SocioGaranteId = 1,
                            Teléfono = "98989898"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rodriguez",
                            DNI = 56565656,
                            Dirección = "San Martin 2435",
                            LocalidadId = 2,
                            Nombre = "Pedro",
                            SocioGaranteId = 1,
                            Teléfono = "45454545"
                        });
                });

            modelBuilder.Entity("NatatorioCEF.Modelos.Cuota", b =>
                {
                    b.HasOne("Presentacion.Modelos.Cobrador", "Cobrador")
                        .WithMany()
                        .HasForeignKey("CobradorId");

                    b.HasOne("Presentacion.Modelos.Socio", "Socio")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Presentacion.Modelos.Socio", b =>
                {
                    b.HasOne("Presentacion.Modelos.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId");

                    b.HasOne("Presentacion.Modelos.Socio", "SocioGarante")
                        .WithMany()
                        .HasForeignKey("SocioGaranteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
